mode: debug #启动模式 debug, release, test
port: :8080 #启动端口
app-name: apiserver-gin #服务名称
url: http://localhost #服务本地地址
max-ping-count: 10 #自检次数
jwt-secret: AC59075B964B0715
language: zh # 项目语言，en或者zh

# 数据库配置（mysql）
database:
  dbname: kubespace-monitor #数据库名称
  host: 127.0.0.1 #数据库服务地址
  port: 3306 #数据库端口
  username: root #用户名(实际线上不可使用root,请授权一个账户)
  password: 123456pass! #密码
  maximum-pool-size: 50  #连接池最大连接数
  maximum-idle-size: 10  #连接池最大空闲数

# 缓存redis配置
redis:
  address: localhost:6379 #redis server地址
  password: 123456 #redis auth 密码，可选，默认无密码
  db: 0 #数据库，可选，默认0
  pool-size: 100 #同一时刻池中最大连接数
  min-idle-conns: 10 #建立连接时维持的最小空闲连接数量，避免新建连接速度慢
  idle-timeout: 3000 #最大空闲时长，单位是秒s

# 日志配置(使用zap&lumberjack)
log:
  development: false
  disable-caller: false
  disable-stacktrace: false
  encoding: json                          # json or console
  level: info                             # 日志级别，INFO, WARN, ERROR
  name: eagle
  writers: file                        # 有2个可选项：file,console 选择file会将日志记录到logger_file指定的日志文件中，选择console会将日志输出到标准输出，当然也可以两者同时选择
  logger-file: ./tmp/log/eagle.log
  logger-warn-file: ./tmp/log/eagle.wf.log
  logger-error-file: ./tmp/log/eagle.err.log
  log-rolling-policy: daily
  LogRotateDate: 1
  LogRotateSize: 1
  LogBaclog-backup-countkupCount: 7

